language: java

java:
  - 11
  
 before_script: 
  - cd zad2

script:
  - mvn test

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: zad2/
  skip_cleanup: true
  on:
    tags: true

