language: java
install: true
jdk:
  - openjdk8
  
script:
  - mvn install

before_deploy:
      - git config --local user.name "209450"
      - git config --local user.email "209450@edu.p.lodz.pl"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: grupa3
  file: /home/travis/build/IIS-ZPI/ZPI_2019_Dzienni_IO1_Grupa3/target/zad2_poprawione-1.0-SNAPSHOT.jar
  skip_cleanup: true
  on:
    branch: Release
    tags: true
  
