language: java

java:
  - 11
  
 before_script: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd zad2_poprawione

script:
  - mvn test -B

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: zad2/
  skip_cleanup: true
  on:
    tags: true

