language: java

java:
  - 8
  
#  before_script: 
#   - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

# script:
#   - mvn test -B

# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: zad2/
#   skip_cleanup: true
#   on:
#     tags: true




